<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<title>Not Permission</title>
<?php
    $base_url=base_url('/static').'/';
?>
<link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>css/custom.css">
<style type="text/css">
.alert{
    position:absolute;
    left:50%;top:40%;
    margin-left:-200px;margin-top:-150px;
    width:400px;
    height:300px;
    line-height:300px;
    border:1px solid #999;
    background-color:#CCC;
    text-align:center;
    font-weight:bold;
    font-size:60px;
}
</style>
</head>
<body>
    <p class="alert">无权限访问</p>
</body>
</html>
